//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class music_table
    {
        public int id { get; set; }
        public string Исполнитель { get; set; }
        public string Наименование_трека { get; set; }
        public string Альбом { get; set; }
        public Nullable<int> Год { get; set; }
    }
}
